x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.3-python3.10
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - postgres
    - redis
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__FERNET_KEY=oiDOlLgcmrDIvlFeq9reMaTzMSaaF18xax53rpK-Y4c=
    - AIRFLOW__CORE__LOGGING_LEVEL=DEBUG
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_job
    - AIRFLOW__WEBSERVER__SECRET_KEY=your_super_secret_key
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data  
    - ./utils:/opt/airflow/utils
    - ./requirements.txt:/opt/airflow/requirements.txt
  logging:
    options:
      max-size: 10m
      max-file: "2"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_job
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    restart: "no"

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
