services:
  db:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    networks:
      - api_net
    command: postgres -N 500
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql@17/data


networks:
  api_net:
    name: ci_net

volumes:
  db_data:
